### ISSUE TITLE
Fill me in!

### ISSUE THREAD

**Issue by darrencauthon** [davidames1983/lang_app#1]
Hey @davidames1983 !!! How's it going!  

You posted an app on Github, awesome!  Fill me in, what's it about? :smile:

**Comment by davidames1983** [comment]
Hey! My brother-in-law and I just started this project last night. I'm
hoping it becomes an effective language learning app, like Rosetta
Stone-ish.

How are you? How's your company?

**Comment by darrencauthon** [comment]
Things are going just fine!  

Sounds like a neat idea for your app.  I'll be watching, good luck!
